// SPDX-License-Identifier: AGPL-3.0-only
// EVERY FIRST-PARTY SOURCE FILE SAYS WHICH LICENCE IT IS UNDER, and this is
// what keeps that true as files are added.
//
// The repository is AGPL-3.0-only: `LICENSE` carries the text and `NOTICE`
// aggregates the third-party licences under `vendor/`. A LICENSE file alone is
// a fact about the repository rather than about a file, and a file is what
// travels — somebody copies one module into their own tree and nothing in it
// says where it came from. So each one opens with the SPDX line.
//
// WHAT IS NOT IN THE WALK, AND WHY EACH ONE IS OUT:
//
//   vendor/   somebody else's code, served as it sits and never edited. Adding
//             a line to it would be editing it, and its licence is the file
//             beside it.
//   vault/    the vault root AS IT SHIPS. Every one of those files is copied
//             verbatim into a person's own folder on first open and is theirs
//             to edit from then on — a licence header on somebody's own
//             `AGENTS.md` or starter section is a claim about their workspace,
//             not about this repository.
//   dist/     generated by `make app`, gitignored, and rewritten every build.
//
// HTML, CSS, YAML and MARKDOWN are out too: the line is a `//` comment, none of
// those four take one, and a `<!-- -->` in a section's markup is a line a page
// author has to read past every time they open the file.

import { test, expect } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL("..", import.meta.url));

/** The directories that hold first-party source. Named rather than derived,
 *  because the answer to "is this ours" is not a property of a path. */
const OURS = ["server", "client", "guest", "contracts", "tools", "tests", "skill", "app"];

const SPDX = "// SPDX-License-Identifier: AGPL-3.0-only";

/** Every `.js`, `.ts` and `.mjs` under `dir`, walked rather than listed — a
 *  list written here is wrong the first time anybody adds a file, which is the
 *  exact failure this test exists to catch. */
function sources(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules") continue;
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) out.push(...sources(path));
    else if (/\.(js|ts|mjs)$/.test(entry)) out.push(path);
  }
  return out;
}

test("every first-party module carries the SPDX line", () => {
  const missing: string[] = [];
  let seen = 0;
  for (const dir of OURS) {
    for (const file of sources(join(HERE, dir))) {
      seen++;
      const lines = readFileSync(file, "utf8").split("\n");
      // FIRST LINE, OR THE ONE AFTER A SHEBANG. A `#!` has to be byte zero or
      // the kernel does not read it, so it is the one thing allowed above.
      const at = lines[0]?.startsWith("#!") ? 1 : 0;
      if (lines[at] !== SPDX) missing.push(file.slice(HERE.length));
    }
  }
  expect(missing).toEqual([]);
  // A walk that found nothing would pass the assertion above and prove nothing.
  expect(seen).toBeGreaterThan(50);
});
