// SPDX-License-Identifier: AGPL-3.0-only
// THE FOURTEENTH CONTRACTS EDIT'S EQUIVALENCE SUITE, AND ITS INSTRUMENTS — not a
// test file, a helper `scopes-equivalence.test.ts` and `e2e/scopes-dom.e2e.ts`
// import (named without `.test.` so `bun test` walks past it).
//
// WHAT IT HOLDS STILL. The fourteenth edit narrows two frozen fields:
// `DrawnSection.vars` and a `Part`'s `vars` carry the entry's OWN variables,
// where they carried the three scopes already merged. The page's values then
// travel once, in `Page.variables`, instead of once per section and once per
// part — which is what made a 649-section page 65 MB on the wire. Everything a
// page, a section script or a plugin is handed must come out the same, and
// "the same" is not argued here: it is captured, from the code as it stood
// BEFORE the change, and every later build is compared with that capture.
//
// THREE GOLDEN SETS, under `fixtures/scopes-golden/`:
//
//   - `scopes.json` — for every page of the corpus, every mount the runtime
//     makes (a slot, a list item, a `data-g-plugin` node, a section script) and
//     the scope and content it is handed, drawn by the REAL `sections.js` over a
//     stand-in document (below); plus `wire/`, the answer the old server gave,
//     so a new runtime can be shown drawing it the same.
//   - `projection/` and `mirror/` — every page's projected markdown and its
//     mirror file, byte for byte.
//   - `dom/` — every page's drawn `#g-page`, from a real browser, normalised.
//
// THE RULE THAT MAKES THEM WORTH ANYTHING: a golden is captured once and never
// regenerated by the change it holds. `GOLDEN_CAPTURE=1` writes a golden that
// is MISSING and never overwrites one that is there; `manifest.json` holds
// every file's digest, and a comparison refuses a golden whose bytes no longer
// match it. Regenerating one is therefore a deleted file and an edited manifest
// in the diff, which is exactly what a reviewer should be made to see.
//
// Every page, word, number and identity in the corpus is invented; the frozen
// copies of the shipped `vault/base/` pages and `vault/design/` are the
// framework's own words, copied as they stood when the goldens were taken.

import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { contentOf, varsOf } from "../server/domain/pages.ts";
import type { Page, Variables } from "../contracts/types.ts";

export const CORPUS = join(import.meta.dir, "fixtures", "scopes-vault");
export const GOLDEN = join(import.meta.dir, "fixtures", "scopes-golden");

/** The integration head the goldens were captured from: S1 and C merged, the
 *  fourteenth edit not begun. */
export const CAPTURED_FROM = "acaa42e";

/** Every page of the corpus, the design doc included. Listed rather than
 *  walked, because each one is a page a golden is kept for and a page added to
 *  the corpus is a golden added on purpose. */
export const CORPUS_PAGES: readonly string[] = Object.freeze([
  "home",
  "home/Shadowing",
  "home/Shadowing/Kid",
  "home/Shadowing/Plain_Kid",
  "home/Values",
  "home/Base_Figure",
  "home/Base_Reveal",
  "home/Base_Diagram",
  "@design",
]);

/** Is this run capturing goldens rather than comparing with them. */
export const capturing = (): boolean => process.env.GOLDEN_CAPTURE === "1";

/** Copy the corpus to `to`, a scratch vault. The corpus itself is never
 *  mounted: a server writes into what it mounts. */
export function copyCorpus(to: string): void {
  mkdirSync(to, { recursive: true });
  cpSync(CORPUS, to, { recursive: true });
}

/** A vault's files WITHOUT A CLOCK. `Child.created` is read off the directory,
 *  and a scratch copy's directories are made on every run, so a golden holding
 *  it would hold the time the test ran. The contract has the field absent
 *  where the store keeps no clock, which is this. */
export function clockless<T extends object>(files: T): T {
  const out = { ...files } as T & { created?: unknown };
  delete out.created;
  return out;
}

/** A page id as a file name: `home/Shadowing` is `home__Shadowing`. */
export const fileOf = (id: string): string => id.replaceAll("/", "__");

/* ── one spelling of a value ─────────────────────────────────────────────── */

/** JSON with every object's keys sorted, at every depth: one value, one text. */
export function stable(v: unknown): string {
  if (v === undefined) return "undefined";
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(stable).join(",")}]`;
  const o = v as Record<string, unknown>;
  return `{${Object.keys(o).sort().map((k) => `${JSON.stringify(k)}:${stable(o[k])}`).join(",")}}`;
}

/** `stable`, indented, for a golden a person may have to read. */
export const pretty = (v: unknown): string => `${JSON.stringify(JSON.parse(stable(v)), null, 2)}\n`;

export const sha = (text: string): string => createHash("sha256").update(text).digest("hex");

/* ── the goldens ─────────────────────────────────────────────────────────── */

interface Manifest {
  capturedFrom: string;
  rule: string;
  files: Record<string, string>;
}

const MANIFEST = join(GOLDEN, "manifest.json");
const RULE =
  "Captured from the code before the fourteenth contracts edit and never regenerated by the change it holds. " +
  "GOLDEN_CAPTURE=1 writes a missing golden and never overwrites one.";

function manifest(): Manifest {
  if (!existsSync(MANIFEST)) return { capturedFrom: CAPTURED_FROM, rule: RULE, files: {} };
  return JSON.parse(readFileSync(MANIFEST, "utf8")) as Manifest;
}

/**
 * THE ONE DOOR TO A GOLDEN. Comparing, it answers the golden's text and throws
 * if the file is missing or its bytes are not the ones the manifest recorded.
 * Capturing, a missing golden is written from `actual` and recorded, and one
 * that is there is left exactly as it is and answered — so a capture run is
 * also a comparison run for everything it did not have to write.
 */
export function golden(rel: string, actual: string): string {
  const at = join(GOLDEN, rel);
  const m = manifest();
  if (!existsSync(at)) {
    if (!capturing()) throw new Error(`no golden at ${rel} — goldens are captured once, before the change, with GOLDEN_CAPTURE=1`);
    mkdirSync(dirname(at), { recursive: true });
    writeFileSync(at, actual, "utf8");
    m.files[rel] = sha(actual);
    const files = Object.fromEntries(Object.entries(m.files).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
    writeFileSync(MANIFEST, `${JSON.stringify({ ...m, files }, null, 2)}\n`, "utf8");
    return actual;
  }
  const text = readFileSync(at, "utf8");
  const want = m.files[rel];
  if (want === undefined) throw new Error(`the golden ${rel} is not in manifest.json — it was not captured by the capture run`);
  if (sha(text) !== want) throw new Error(`the golden ${rel} was changed after it was captured — goldens are never regenerated by the change they hold`);
  return text;
}

/** A golden that is only ever READ, capturing or not: one captured by the
 *  other half of the suite, which this half compares with and never writes. */
export function held(rel: string): string {
  const at = join(GOLDEN, rel);
  if (!existsSync(at)) throw new Error(`no golden at ${rel} — it is captured by the other half of the suite`);
  const text = readFileSync(at, "utf8");
  if (sha(text) !== manifest().files[rel]) throw new Error(`the golden ${rel} was changed after it was captured`);
  return text;
}

/* ── the wire ────────────────────────────────────────────────────────────── */

/** The part of a `page.read` answer the runtime draws and projects from. */
export interface Wire {
  id: string;
  name: string;
  plugin: string;
  variables: Variables;
  sections: Page["sections"];
}

export const wireOf = (page: Page): Wire => ({
  id: page.id,
  name: page.name,
  plugin: page.plugin,
  variables: page.variables,
  sections: page.sections,
});

/**
 * THE SAME PAGE, AS THE FOURTEENTH EDIT SPELLS IT: each section's `vars` its
 * own `variables:`, each part's (list items included) its content's own, `{}`
 * where it has none. Derived from the document each `DrawnSection` carries in
 * `source`, never from the merged values, so it cannot inherit a merge.
 */
export function ownWire(wire: Wire): Wire {
  const sections = wire.sections.map((s) => {
    const source = s.source;
    const parts: Record<string, unknown> = {};
    for (const [slot, part] of Object.entries(s.parts)) {
      const held = source.parts?.[slot];
      if (part.kind === "list") {
        const items = (Array.isArray(held) ? held : []).map((one) => contentOf(one)).filter((c) => c !== null);
        if (items.length !== part.items.length) throw new Error(`${wire.id} ${s.name}.${slot}: the list's items do not line up with its document`);
        parts[slot] = { ...part, items: part.items.map((item, i) => ownPart(item, items[i]?.variables)) };
      } else {
        parts[slot] = ownPart(part, Array.isArray(held) ? undefined : contentOf(held)?.variables);
      }
    }
    return { ...s, vars: varsOf(source.variables), parts } as typeof s;
  });
  return { ...wire, sections };
}

function ownPart<P extends { kind: string }>(part: P, own: Variables | undefined): P {
  return "vars" in part ? { ...part, vars: varsOf(own) } : part;
}

/* ── the real runtime, over a stand-in document ──────────────────────────── */

/** What one mount was handed. `via` says which door: a `slot`, a list `item`,
 *  a `data-g-plugin` `node`, or a section `script`. */
export interface Mount {
  via: "slot" | "item" | "node" | "script";
  section: string;
  part: string | null;
  item: number | null;
  node: string | null;
  ctx: unknown;
  content: unknown;
}

export interface DrawnRecord {
  name: string;
  /** The section's markup after `{{name}}` was resolved, as a digest. */
  markup: string;
  mounts: Mount[];
}

const VOID = new Set(["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"]);

/**
 * A STAND-IN FOR THE BOX'S DOCUMENT: elements, attributes, a tree, and the
 * handful of calls `sections.js` makes — no layout, no text nodes, no events.
 * Enough to run the real `draw` and `fillSlots` in bun, so a change to either
 * is exercised without a browser; `e2e/scopes-dom.e2e.ts` is the real browser.
 */
class El {
  tagName: string;
  attrs = new Map<string, string>();
  kids: El[] = [];
  parent: El | null = null;
  own = "";
  content: El | null = null;
  constructor(tag: string, private readonly doc: FakeDoc) {
    this.tagName = tag.toLowerCase();
    if (this.tagName === "template") this.content = new El("#fragment", doc);
  }
  get id(): string {
    return this.attrs.get("id") ?? "";
  }
  set id(v: string) {
    this.attrs.set("id", v);
  }
  setAttribute(n: string, v: unknown): void {
    this.attrs.set(n.toLowerCase(), String(v));
  }
  getAttribute(n: string): string | null {
    return this.attrs.get(n.toLowerCase()) ?? null;
  }
  hasAttribute(n: string): boolean {
    return this.attrs.has(n.toLowerCase());
  }
  removeAttribute(n: string): void {
    this.attrs.delete(n.toLowerCase());
  }
  get attributes(): { name: string; value: string }[] {
    return [...this.attrs].map(([name, value]) => ({ name, value }));
  }
  get dataset(): Record<string, string> {
    const out: Record<string, string> = {};
    for (const [n, v] of this.attrs) {
      if (n.startsWith("data-")) out[n.slice(5).replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())] = v;
    }
    return out;
  }
  get textContent(): string {
    return this.own + this.kids.map((k) => k.textContent).join("");
  }
  set textContent(v: string) {
    for (const k of this.kids) k.parent = null;
    this.kids = [];
    this.own = String(v ?? "");
  }
  set innerHTML(html: string) {
    this.doc.markup.push(html);
    const into = this.content ?? this;
    into.textContent = "";
    parseInto(into, html, this.doc);
  }
  appendChild(c: El): El {
    if (c.tagName === "#fragment") {
      for (const k of [...c.kids]) this.appendChild(k);
      return c;
    }
    c.remove();
    c.parent = this;
    this.kids.push(c);
    // A script appended to the document runs, which is how a section script's
    // bindings are claimed — so appending one here claims them.
    if (c.tagName === "script") this.doc.ran(c);
    return c;
  }
  replaceChildren(...nodes: El[]): void {
    this.textContent = "";
    for (const n of nodes) this.appendChild(n);
  }
  remove(): void {
    if (this.parent === null) return;
    const at = this.parent.kids.indexOf(this);
    if (at >= 0) this.parent.kids.splice(at, 1);
    this.parent = null;
  }
  contains(n: El | null): boolean {
    for (let at = n; at !== null; at = at.parent) if (at === this) return true;
    return false;
  }
  querySelectorAll(selector: string): El[] {
    const test = matcher(selector);
    const out: El[] = [];
    const walk = (el: El): void => {
      for (const k of el.kids) {
        if (test(k)) out.push(k);
        walk(k);
      }
    };
    walk(this);
    return out;
  }
  querySelector(selector: string): El | null {
    return this.querySelectorAll(selector)[0] ?? null;
  }
}

/** `[attr]`, `[attr="value"]` and a bare tag: every selector `sections.js` asks. */
function matcher(selector: string): (el: El) => boolean {
  const attr = /^\[([\w-]+)(?:="([^"]*)")?\]$/.exec(selector.trim());
  if (attr) return (el) => el.attrs.has(attr[1] as string) && (attr[2] === undefined || el.attrs.get(attr[1] as string) === attr[2]);
  if (/^[a-z][\w-]*$/i.test(selector.trim())) return (el) => el.tagName === selector.trim().toLowerCase();
  throw new Error(`the stand-in document cannot answer the selector ${selector}`);
}

function attrsInto(el: El, text: string): void {
  const re = /([^\s=/"'>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g;
  for (let m = re.exec(text); m !== null; m = re.exec(text)) {
    el.attrs.set((m[1] as string).toLowerCase(), m[2] ?? m[3] ?? m[4] ?? "");
  }
}

/** Elements and their nesting, and a script's or a style's text; nothing else
 *  is kept. Comments go first, so markup quoted in one is not an element. */
function parseInto(root: El, html: string, doc: FakeDoc): void {
  const src = html.replace(/<!--[\s\S]*?-->/g, "");
  const re =
    /<(script|style)\b((?:[^>"']|"[^"]*"|'[^']*')*)>([\s\S]*?)<\/\1\s*>|<\/([A-Za-z][\w:-]*)\s*>|<([A-Za-z][\w:-]*)((?:[^>"']|"[^"]*"|'[^']*')*?)(\/?)>/g;
  const stack: El[] = [root];
  for (let m = re.exec(src); m !== null; m = re.exec(src)) {
    const top = stack[stack.length - 1] as El;
    if (m[1] !== undefined) {
      const el = new El(m[1], doc);
      attrsInto(el, m[2] ?? "");
      el.own = m[3] ?? "";
      el.parent = top;
      top.kids.push(el);
      continue;
    }
    if (m[4] !== undefined) {
      const tag = m[4].toLowerCase();
      for (let i = stack.length - 1; i > 0; i--) {
        if ((stack[i] as El).tagName === tag) {
          stack.length = i;
          break;
        }
      }
      continue;
    }
    const el = new El(m[5] as string, doc);
    attrsInto(el, m[6] ?? "");
    el.parent = top;
    top.kids.push(el);
    if (m[7] !== "/" && !VOID.has(el.tagName)) stack.push(el);
  }
}

class FakeDoc {
  markup: string[] = [];
  constructor(private readonly onScript: (n: number) => void) {}
  createElement(tag: string): El {
    return new El(tag, this);
  }
  ran(script: El): void {
    const n = /__gRuntime\.claim\((\d+)\)/.exec(script.own);
    if (n) this.onScript(Number(n[1]));
  }
}

const SECTIONS_JS = join(import.meta.dir, "..", "guest", "runtime", "sections.js");

/**
 * DRAW A PAGE WITH THE REAL `sections.js` and answer every mount it made.
 *
 * The runtime is evaluated fresh for each page, over the stand-in document,
 * with a registry in which every plugin and every part kind is a recorder: it
 * draws nothing and keeps what it was handed. `pageVars` is what `boot.js`
 * hands the draw, the answer's `variables`.
 */
export function drawnMounts(wire: Wire): { sections: DrawnRecord[]; said: string[] } {
  const rt: Record<string, unknown> = {};
  const said: string[] = [];
  let current: { mounts: Mount[]; items: Map<string, number> } = { mounts: [], items: new Map() };
  const doc = new FakeDoc((n) => {
    const got = (rt.claim as (n: number) => { ctx: { section: string; vars: unknown } } | null)(n);
    if (got) current.mounts.push({ via: "script", section: got.ctx.section, part: null, item: null, node: null, ctx: got.ctx.vars, content: null });
  });
  const recorder = (id: string) => ({
    id,
    mount(node: El, content: unknown, ctx: { section: string; part: string | null; vars: unknown }) {
      let via: Mount["via"] = "slot";
      let item: number | null = null;
      if (ctx.part === null) via = "node";
      else if (node.parent === null) {
        // A list item's holder is mounted before it is put in the slot.
        via = "item";
        const key = `${ctx.section} ${ctx.part}`;
        item = current.items.get(key) ?? 0;
        current.items.set(key, item + 1);
      }
      current.mounts.push({
        via,
        section: ctx.section,
        part: ctx.part,
        item,
        node: via === "node" ? node.getAttribute("data-g-plugin") : null,
        ctx: ctx.vars,
        content,
      });
    },
  });
  rt.plugins = {
    forKind: (kind: string) => recorder(`kind:${kind}`),
    get: (id: string) => recorder(id),
    reach: (id: string) => recorder(id),
    ids: () => [],
  };
  rt.effects = { onTeardown() {}, remember() {}, disposeAll() {} };
  rt.report = (message: string) => void said.push(message);

  const glob = globalThis as Record<string, unknown>;
  const was = glob.__gRuntime;
  glob.__gRuntime = rt;
  try {
    new Function("document", "CSS", readFileSync(SECTIONS_JS, "utf8"))(doc, {
      escape: (s: string) => s.replace(/[^\w-]/g, (c) => `\\${c}`),
    });
  } finally {
    glob.__gRuntime = was;
  }
  const sections = rt.sections as { draw: (drawn: unknown, env: unknown) => unknown };

  const root = doc.createElement("main");
  const env = { page: wire.id, root, pageVars: wire.variables || {}, call: () => Promise.resolve(null), dress() {} };
  const out: DrawnRecord[] = [];
  for (const section of wire.sections) {
    current = { mounts: [], items: new Map() };
    doc.markup = [];
    sections.draw(section, env);
    out.push({ name: section.name, markup: sha(doc.markup[0] ?? ""), mounts: current.mounts });
  }
  // Round-tripped, so what is compared is what a golden can hold.
  return JSON.parse(JSON.stringify({ sections: out, said })) as { sections: DrawnRecord[]; said: string[] };
}

/* ── a page like Talks ───────────────────────────────────────────────────── */

/** The shape measured on the owner's Talks page: 649 sections, each a child's
 *  row drawn with the default section, under about 95 KB of page variables. */
export const TALKS = Object.freeze({ id: "home/Talks", sections: 649, varBytes: 95_000 });

/**
 * WRITE A VAULT HOLDING ONE PAGE THE SHAPE OF TALKS, deterministically: a root,
 * the page, and 649 children, each held by a section of its own. Its own vault
 * rather than the corpus's, so the corpus's root does not grow a child row.
 */
export function inventTalks(vault: string): void {
  const home = join(vault, "pages", "home");
  mkdirSync(home, { recursive: true });
  writeFileSync(
    join(home, "content.yaml"),
    ["name: Invented Root", "uid: scopestalksroot01", "plugin: biom-doc", "contents:", "  - name: body", "    parts:", "      body: An invented root.", ""].join("\n"),
    "utf8",
  );
  const talks = join(home, "children", "Talks");
  mkdirSync(talks, { recursive: true });
  const rooms = ["North", "South", "East", "West", "Upper", "Lower"];
  const speakers: string[] = [];
  for (let i = 0; speakers.join("").length < TALKS.varBytes - 2_000; i++) {
    speakers.push(`Invented Speaker ${String(i).padStart(4, "0")} of the ${rooms[i % rooms.length]} room, on a subject nobody has given, for about forty minutes`);
  }
  const lines = [
    "name: Talks",
    "uid: scopestalks01",
    "plugin: biom-doc",
    "variables:",
    "  venue: The Invented Hall",
    "  year: 2026",
    "  speakers:",
    ...speakers.map((s) => `    - ${s}`),
    "contents:",
    "  - name: intro",
    "    parts:",
    "      body: Every talk at {{venue}} in {{year}}, invented.",
  ];
  for (let i = 1; i <= TALKS.sections; i++) {
    const seg = `Talk_${String(i).padStart(3, "0")}`;
    lines.push(`  - name: "@page-${seg}"`, "    parts:", "      body:", "        type: child", `        data: ${seg}`);
    const dir = join(talks, "children", seg);
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      join(dir, "content.yaml"),
      [`name: Talk ${i}`, `uid: scopestalk${String(i).padStart(4, "0")}`, "plugin: biom-doc", "contents:", "  - name: body", "    parts:", `      body: Invented talk ${i}, at {{venue}}.`, ""].join("\n"),
      "utf8",
    );
  }
  lines.push("");
  writeFileSync(join(talks, "content.yaml"), lines.join("\n"), "utf8");
}

/** Every `html` string an answer carries — section markup, an html part's, a
 *  child's own drawing — in bytes. What the fourteenth edit is about is the
 *  rest of the answer, so the size check is taken without it. */
export function markupBytes(wire: Wire): number {
  let n = 0;
  const len = (s: unknown): number => (typeof s === "string" ? Buffer.byteLength(JSON.stringify(s)) : 0);
  const part = (p: Record<string, unknown>): void => {
    n += len(p.html);
    const draw = p.draw as { html?: unknown } | undefined;
    if (draw) n += len(draw.html);
    if (Array.isArray(p.items)) for (const i of p.items) part(i as Record<string, unknown>);
  };
  for (const s of wire.sections) {
    n += len(s.html);
    for (const p of Object.values(s.parts)) part(p as unknown as Record<string, unknown>);
  }
  return n;
}
